Move user configuration from main script to separate config file

diff --git a/dockback b/dockback
--- a/dockback
+++ b/dockback
@@ -10,30 +10,19 @@
 #===============================================================================
 
 #-------------------------------------------------------------------------------
-#  User-defined variables
-#-------------------------------------------------------------------------------
-
-share_remote_path='//ad.domain.tld/DFS/Share/Docker Backups'
-share_username='BackupUser'
-share_password='BackupPassw0rd'
-share_domain='ad.domain.tld'
-
-email_enabled=true
-email_server='smtp.ad.domain.tld'
-email_port='25'
-email_from='do-not-reply@domain.tld'
-email_to='admin@domain.tld'
-email_subject='dockback report'
-
-backup_jobs[0]='job_name=webapp|job_type=compress_directory|directory_path=/docker/webapp'
-backup_jobs[1]='job_name=webapp-db|job_type=mysql_dump|container_name=webapp-db|db=webappdb|compress=true'
-backup_jobs[2]='job_name=confluence|job_type=file_copy|file_path=/docker/confluence/home/backups/*.zip|delete_after_copy=false'
-
-#-------------------------------------------------------------------------------
 #  Internally-defined variables
 #-------------------------------------------------------------------------------
 
+# Path at which `share_remote_path` will be mounted. Will be created if it does
+# not already exist.
 share_mount_point='/mnt/shares/dockback'
+
+# Path from which user configurations will be imported.
+config_path='/opt/dockback/config'
+
+# Start the script with no warnings or errors
+warnings=0
+errors=0
 
 #===  FUNCTION  ================================================================
 #         NAME:  display_usage
@@ -126,6 +115,25 @@ END_OF_USAGE
 }
 
 #===  FUNCTION  ================================================================
+#         NAME:  get_config
+#  DESCRIPTION:  Import and check the dockback configuration file.              # config validation not yet implemented
+#===============================================================================
+get_config() {
+    echo -n "[I] Importing configuration file... "
+    if [[ -e $config_path ]]; then
+        source $config_path
+        echo "Done"
+    else
+        echo "Failed"
+        echo "[E] Exiting because configuration file '$config_path' is missing."
+        ((errors++))
+        email_alerts
+        display_alerts
+        exit 1
+    fi
+}
+
+#===  FUNCTION  ================================================================
 #         NAME:  get_value
 #  DESCRIPTION:  Parse a job string to retrieve the value of a given key.
 # PARAMETER  1:  job
@@ -147,28 +155,28 @@ get_value() {
 #===============================================================================
 get_job() {
     printf '%s\n' "${backup_jobs[@]}" |  # Display the array
-        grep ^job_name=$1\|               # Select the job containing job_name
+        grep ^job_name=$1\|              # Select the job containing job_name
 }
 
 #===  FUNCTION  ================================================================
 #         NAME:  schedule_script
-#  DESCRIPTION:  Schedule the script to run every 4 hours.
+#  DESCRIPTION:  Schedule the script to run every 6 hours.
 #===============================================================================
 schedule_script() {
-    # Get the file path of this script
-    local script_path=$(readlink -f $0)
+    local script_path='/usr/local/sbin/dockback'
+    local cron_path='/etc/cron.d/dockback'
+    local cron_job="0 */6 * * * root [ -x $script_path ] && $script_path up all"
 
-    # Check whether script_path is currently scheduled
-    if [[ $(crontab -l | grep $script_path) ]]; then
-        # script_path is scheduled
+    # Check if script_path is scheduled
+    if grep -Fxq "$cron_job" "$cron_path"; then
         echo "[I] '$script_path' is already scheduled."
     else
-        # script_path is not scheduled
         echo -n "[W] '$script_path' is not scheduled. Scheduling... "
         ((warnings++))
-        (crontab -l 2>/dev/null; echo "0 */4 * * * $script_path") | crontab -
-        # Verify script_path was scheduled
-        if [[ $(crontab -l | grep $script_path) ]]; then
+        # Replace the file (if it exists) with cron_job
+        echo "$cron_job" > $cron_path
+        # Make sure it worked
+        if grep -Fxq "$cron_job" $cron_path; then
             echo "Done"
         else
             echo "Failed"
@@ -499,13 +507,11 @@ cleanup_jobs() {
 #  Script body
 #-------------------------------------------------------------------------------
 
-warnings=0
-errors=0
-
 case "$1" in
     up )
         case "$2" in
             all )
+                get_config
                 check_dependencies
                 mount_share
                 execute_jobs
@@ -520,6 +526,7 @@ case "$1" in
                         display_usage up job
                         ;;
                     * )
+                        get_config
                         check_dependencies
                         mount_share
                         execute_job "$3"
@@ -624,12 +631,14 @@ case "$1" in
     test )
         case "$2" in
             email )
+                get_config
                 check_dependencies
                 email_alerts
                 display_alerts
                 exit 0
                 ;;
             share )
+                get_config
                 check_dependencies
                 mount_share
                 unmount_share
